theme: jekyll-theme-slate
title: Welcome to Connor's Personal Website
description: I am a Sophomore Math and Computer Science Major at Bowdoin College with a strong interest in their intersection. Bookmark this page to find out more about my work.
